version: '3.5'

services:
  app:
    image: hanabosocom/php-dev:php-7.4
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/var/www
      - ${SSH_AUTH_SOCK}:${SSH_AUTH}
      - ${HOME}/dev/.composer:${HOME}/dev/.composer
    environment:
      - APP_ENV=dev
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - COMPOSER_HOME=${HOME}/dev/.composer
      - KERNEL_CLASS=UserBundleTests\Kernel
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MONGODB_DSN=mongodb://mongo
      - MONGODB_DB=user
      - MARIADB_DSN=mariadb
      - MARIADB_DB=user
      - MARIADB_USER=root
      - MARIADB_PASS=root

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db

  mariadb:
      image: mariadb:latest
      command: "mysqld --innodb_flush_method=nosync"
      environment:
       MYSQL_ROOT_PASSWORD: root
      volumes:
       - mariadb:/var/lib/mysql

volumes:
  mongo: {}
  rabbit-mq: {}
  mariadb: {}
