version: '3.5'

services:
  app:
    image: hanabosocom/php-dev:php-8.2-alpine
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/var/www:cached
      - ${SSH_AUTH}:/tmp/.ssh-auth-sock
      - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
    environment:
      - APP_ENV=dev
      - DEV_UID=${DEV_UID}
      - DEV_GID=${DEV_GID}
      - COMPOSER_HOME=${HOME}/dev/.composer
      - KERNEL_CLASS=UserBundleTests\Kernel
      - SMTP_DSN=${SMTP_DSN}
      - MONGODB_DSN=mongodb://mongo
      - MONGODB_DB=user
      - MARIADB_DSN=mariadb
      - MARIADB_DB=user
      - MARIADB_USER=root
      - MARIADB_PASS=root
      - JWT_KEY=1234567890123456789012345678901234567890012345678900123456789012

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db

  mariadb:
      image: mariadb:latest
      command: "mysqld --innodb_flush_method=nosync"
      environment:
       MYSQL_ROOT_PASSWORD: root
      volumes:
       - mariadb:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog

volumes:
  mongo: {}
  rabbit-mq: {}
  mariadb: {}
