services:
    _defaults:
        public: '%public.services%'

    Hanaboso\UserBundle\Controller\UserController:
        class: Hanaboso\UserBundle\Controller\UserController
        arguments:
            - '@hbpf.user.handler.user'
        calls:
            - ['setContainer', ['@service_container']]
