services:
    _defaults:
        public: '%public.services%'

    hbpf.user.handler.user:
        class: Hanaboso\UserBundle\Handler\UserHandler
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.manager.user'
            - '@hbpf.user.provider.resource'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.user.manager.token:
        class: Hanaboso\UserBundle\Model\Token\TokenManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.provider.resource'

    hbpf.user.manager.user:
        class: Hanaboso\UserBundle\Model\User\UserManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.manager.security'
            - '@hbpf.user.manager.token'
            - '@event_dispatcher'
            - '@hbpf.user.provider.resource'
            - '@hbpf.user.mailer'
            - '%frontendHost%'
            - '%activateLink%'
            - '%passwordLink%'

    hbpf.user.manager.security:
        class: Hanaboso\UserBundle\Model\Security\SecurityManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@security.password_hasher_factory'
            - '@hbpf.user.provider.resource'
            - '@request_stack'
            - '@config.jwt'
            - '%cookieSameSite%'

    Hanaboso\UserBundle\Model\Security\JWTAuthenticator:
        class: Hanaboso\UserBundle\Model\Security\JWTAuthenticator
        arguments:
            - '@hbpf.user.manager.security'

    hbpf.user.provider.resource:
        class: Hanaboso\UserBundle\Provider\ResourceProvider
        arguments:
            - '%db_res%'

    hbpf.user.mailer:
        class: Hanaboso\UserBundle\Model\Mailer\Mailer
        arguments:
            - '@rabbit_mq.publisher.pipes.messages'
            - '@EmailServiceBundle\Handler\MailHandler'
            - '%mailer_from%'
            - '%mailer_async%'
            - '%mailer_builder_id%'

    EmailServiceBundle\Transport\Impl\SymfonyMailerTransport:
        class: EmailServiceBundle\Transport\Impl\SymfonyMailerTransport
        arguments:
            - '@mailer.mailer'
        calls:
            - ['setLogger', ['@monolog.logger.mailer']]
